server:
  port: 80
spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
    gateway:
      discovery:
        locator:
          enabled: true
          #lower-case-service-id: true
      routes:
        - id: openapi
          uri: lb://api-gateway
          predicates:
          - Path=/v3/api-docs/**
          filters:
          - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
sleuth:
  sampler:
    probability: 1.0
springdoc:
  show-actuator: true
